name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE    
    
    - name: Restore dependencies
      run: |
        dotnet restore Avalara.AvaTax.Net20.sln
        dotnet restore Avalara.AvaTax.net45.sln
        dotnet restore Avalara.AvaTax.netstandard11.sln
    - name: Build
      run: |
          msbuild.exe Avalara.AvaTax.Net20.sln /p:platform="Any CPU" /p:configuration="Release"
          msbuild.exe Avalara.AvaTax.net45.sln /p:platform="Any CPU" /p:configuration="Release"
          msbuild.exe Avalara.AvaTax.net461.sln /p:platform="Any CPU" /p:configuration="Release"         
          dotnet build Avalara.AvaTax.netstandard11.sln -c Release
          dotnet build Avalara.AvaTax.netstandard20.sln -c Release
        
   
